### ISSUE TITLE
Detecting if a given 2D coordinate is inside a polygon drawn by XIVPaint

### ISSUE THREAD

**Issue by uiharuayako** [ArchiDog1998/XIVPainter#3]
During development, I want to execute certain actions when the user hovers the mouse over or clicks on a shape drawn by XIVPaint. However, I've encountered difficulties. Specifically, I am unsure how to determine if a given 2D coordinate lies within a polygon drawn by XIVPaint.  

I have considered using the "Ray-casting Algorithm" to determine whether a point is inside a polygon. The basic idea is to cast a ray in any direction from the point to be tested, and then count the number of intersections between the ray and all edges of the polygon. If the number of intersections is odd, the point is considered to be inside the polygon; if it's even, the point is considered to be outside the polygon. Here is the code:
```
public static bool IsPointInPolygon(Vector2 point, Vector2[] polygon)
{
    int i, j;
    bool result = false;
    for (i = 0, j = polygon.Length - 1; i < polygon.Length; j = i++)
    {
        if ((polygon[i].Y > point.Y) != (polygon[j].Y > point.Y) &&
            (point.X < (polygon[j].X - polygon[i].X) * (point.Y - polygon[i].Y) / (polygon[j].Y - polygon[i].Y) + polygon[i].X))
        {
            result = !result;
        }
    }
    return result;
}
```
However, your code is quite sophisticated and as a beginner in C#, I'm unsure of how to apply this method to instances of the Drawing3DCircularSectorO type.  

Any guidance on this matter would be greatly appreciated.

**Comment by Ted-Jin-Lab** [comment]
所以为啥两个华人要用英语交流？
你是需要Polygon添加一个方法，可以识别输入的平面点是否在该多边形内是吧？
还是你只需要判断当前鼠标是否在范围内？

**Comment by uiharuayako** [comment]
对于我的需求，这两种方法都可以，需要执行的逻辑写在ImGui.IsMouseClicked里，只要能判断鼠标在屏幕上的坐标在多边形里就行。

**Comment by Ted-Jin-Lab** [comment]
OK. 明天整个。

**Comment by uiharuayako** [comment]
thx，帮助很大

**Comment by Ted-Jin-Lab** [comment]
我我我，还没测试呢，运行没问题？

**Comment by uiharuayako** [comment]
运行完全正常，达到了期望的效果，很棒（
