### ISSUE TITLE
How to Draw Tethers Vfx

### ISSUE THREAD

**Issue by Small-Miao** [ArchiDog1998/XIVPainter#5]
I want draw Tethers Vfx on game.
but i dont find Tethers vfx path in game.

**Comment by Small-Miao** [comment]
没事了 看到新添加的doc了 打扰了

**Comment by Ted-Jin-Lab** [comment]
Chinese?

关于连线的内容，在游戏名称中为`Channeling`，可以参考这个文档：https://github.com/xivapi/ffxiv-datamining/blob/master/csv/Channeling.csv
在XIVPainter里面，只内置了一种连线。
``` c#
new ActorVfx(ActorOmen.ChannelingDark.Channeling(), player, target);
```
这个函数是将Channeling的名称转换为路径的函数，你可以用自己的名称来调用这个[Channeling](https://github.com/ArchiDog1998/XIVPainter/blob/35090a7e6d4340cc65a48a3cb1ad66de80dafa14/XIVPainter/Vfx/ActorOmen.cs#L57C26-L57C36)函数。

你可以尝试这么使用：
``` c#
new ActorVfx("chn_wind001f".Channeling(), player, target);
```
Have fun!
