### ISSUE TITLE
绘制时出现问题导致游戏崩溃

### ISSUE THREAD

**Issue by Small-Miao** [ArchiDog1998/XIVPainter#6]
2024-04-20 23:00:10.158 +08:00 [ERR] Exception during raise of Void <InvokeSafely>b__0()
System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at XIVDrawer.Vfx.ActorVfx.AdditionalDispose() in D:\Code\ffxiv\NyaDraw\XIVPainter\XIVDrawer\Vfx\ActorVfx.cs:line 45
   at XIVDrawer.BasicDrawing.Dispose() in D:\Code\ffxiv\NyaDraw\XIVPainter\XIVDrawer\BasicDrawing.cs:line 50
   at XIVDrawer.BasicDrawing.Framework_Update(IFramework framework) in D:\Code\ffxiv\NyaDraw\XIVPainter\XIVDrawer\BasicDrawing.cs:line 31
   at Dalamud.Utility.EventHandlerExtensions.HandleInvoke(Action act)
然后就崩溃了

**Comment by Ted-Jin-Lab** [comment]
在开发吗？你需要确认一下该ActorVfx是否系统会自动删除，如果会的话，不要手动删除。创建的时候有个是否删除的选项，留意一下。
https://github.com/ArchiDog1998/XIVDrawer/blob/ed7d2ddbdfd54b5501b50e1302ba6550ba9f1ef5/XIVDrawer/Vfx/ActorVfx.cs#L27

**Comment by Small-Miao** [comment]
哦哦 你是指DeathTime 那个设置吗 如果设置了的话是不是就会崩溃

**Comment by Small-Miao** [comment]
```
  private static void drawOmen(GameObject targetObject, DrawElement e)
  {
      if (e.drawOnObject)
      {
          StaticVfx vfx = new StaticVfx(OmenHelper.Omen(e.drawAvfx), targetObject, new System.Numerics.Vector3(e.raduisX, e.raduisY, e.raduisZ));
          vfx.DeadTime = DateTime.Now.AddMilliseconds(e.destoryTime);
      }
      else
      {
          StaticVfx vfx = new StaticVfx(OmenHelper.Omen(e.drawAvfx), new Vector3(e.refX, e.refY, e.refZ), e.refRotation, new System.Numerics.Vector3(e.raduisX, e.raduisY, e.raduisZ));
          vfx.DeadTime = DateTime.Now.AddMilliseconds(e.destoryTime);
      }
  }

  private static void drawLockOn(GameObject targetObject,GameObject castObject,DrawElement e)
  {
      if (castObject == null)
      {
          castObject = targetObject;
      }
      ActorVfx avfx = new ActorVfx(OmenHelper.LockOn(e.drawAvfx), castObject, targetObject);
      avfx.DeadTime = DateTime.Now.AddMilliseconds(e.destoryTime);
  }

  private static void drawChanneling(GameObject targetObject, GameObject castObject, DrawElement e)
  {
      if (castObject == null)
      {
          castObject = targetObject;
      }
      ActorVfx actorVfx = new ActorVfx(OmenHelper.Channeling(e.drawAvfx), castObject, targetObject);
      actorVfx.DeadTime = DateTime.Now.AddMilliseconds(e.destoryTime);
  }
  private static void drawRawAvfx(GameObject targetObject, GameObject castObject, DrawElement e)
  {
      if (castObject == null)
      {
          castObject = targetObject;
      }
      ActorVfx actorVfx = new ActorVfx(e.drawAvfx, castObject, targetObject);
      actorVfx.DeadTime = DateTime.Now.AddMilliseconds(e.destoryTime);
  }
```

**Comment by Ted-Jin-Lab** [comment]
不是，看我发的链接。有个ShouldRemove的参数，需要一个一个测试的。

**Comment by Small-Miao** [comment]
哦哦 那这个报错是因为手动移除的时候因为特效已经被移除了所以报错了？

**Comment by Ted-Jin-Lab** [comment]
是的，所以在尝试释放早已释放的内存，就是那个报错了。

**Comment by Small-Miao** [comment]
之前用上一个版本的时候就没出现这个问题 这个插件是新写的 结果同样的特效同样的绘制方法就有了不同的结果
如果说我全部不自动释放的话是不是会导致内存爆炸

**Comment by Ted-Jin-Lab** [comment]
这个问题是概率出现的，我之前有问题的版本，有的时候不会出现，有的时候十分钟就出现了。就看你free的地方有没有被保护。
如果你不释放的话，不是内存爆炸的问题，可能是玩家头上顶着一堆特效消不掉的问题。我之前测试FF16那个任务的时候就出现了。不得不重启游戏了，找不到地方释放了。

**Comment by Small-Miao** [comment]
他这个释放貌似系统也不是第一时间就释放 而是根据一定时间后释放 你也不确定如果你先释放会发生什么问题 好怪啊

**Comment by Ted-Jin-Lab** [comment]
哎~目前就只能说，它会释放的（不管什么时候），咱就不是放了，让他播放完。不然很可能打了一半，就崩溃了。

**Comment by Small-Miao** [comment]
太抽象了 我刚才测试了下 又不会崩溃了 太离谱了

**Comment by Small-Miao** [comment]
OK 简单的测试了下 如果设置sholdRemove 为 true 你的播放时间 < 释放的时间 就会崩溃
如果能做个检测就好了 主要是你也不知道AVFX的时间长度

**Comment by Small-Miao** [comment]
```
{
    "Filter":{
        "OnlyVisible":true
    },
    "Draw":{
        "castFilter":{
            "OnlyVisible":true,
            "RefActorType":"DataID",
            "RefActorID":"16171"
        },
        "drawType":"RawAvfx",
        "drawAvfx":"vfx/monster/gimmick4/eff/n5ra_b2_g11c0c.avfx",
        "destoryTime":"7000"
    }
}
```
这是我的绘制参数 如果destoryTime <6000 就不会出现问题 如果大于就会崩溃

**Comment by Small-Miao** [comment]
Splatoon 有可以查看VFX 列表的工具
https://github.com/PunishXIV/Splatoon/blob/main/Splatoon/Memory/AttachedInfo.cs#L98
感觉您可以看一下 感谢您的这个库
