### ISSUE TITLE
NyaDraw事项

### ISSUE THREAD

**Issue by Small-Miao** [ArchiDog1998/XIVPainter#7]
ND最开始确实实用的XIVDrawer 
但是由于更新慢 效果不好 无法自定义
所以我自己重新写了个NRender
功能均为自己实现
其中VFX的调用使用查表 只能说就那点特效
所以没有什么所谓的借鉴一说 感谢

**Comment by Small-Miao** [comment]
![image](https://github.com/user-attachments/assets/a6dac232-881f-4c26-9ea5-660bcbea73e7)

**Comment by Ted-Jin-Lab** [comment]
Woc那看来我确实是说对了。先是用了我的库，后来觉得我的不够好，根据我的进行了一定的自定义，那确实证实了我的说法。
没想到这个事情惊动作者了，我也只是在B站上刷到视频了，随口一说，感谢自证！

**Comment by Small-Miao** [comment]
是的 最开始不是和你讨论过ActorVFX的事情吗。 确实不好 后面采用了新的方案。
后面所有的HOOK应该和你用的不是一个。

**Comment by Ted-Jin-Lab** [comment]
对，是的，我研究了一段时间ActorVFX了以后就没继续研究了。能做出来挺好，而且我的库能够给你带来启发也是我的荣幸！

**Comment by Small-Miao** [comment]
好的 那我就Close Issuse了

**Comment by Small-Miao** [comment]
补充一嘴 NRender是全新的库

**Comment by Small-Miao** [comment]
根据我的进行了一定的自定义 这个说法不准确  准确来说是重写了所有 哈哈哈哈  边研究边写的

**Comment by Ted-Jin-Lab** [comment]
挺好的！看得出来做了很多优化！这方面比我厉害！
听起来就像是Rotation Solver Reborn和我的Rotation Solver的关系一样。只有理念和概念留下了，其他的全改了。
